config/routes.rb
Omrails::Application.routes.draw do

  resources :tickets

  get "pages/about"

  devise_for :users

  root :to => 'pages#home'
  get "about" => "pages#about"
  

  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	attr_accessible :description

	validates :description, presence: true

	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
   def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_filter :authenticate_user!, except: [:index]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    #@tickets = current_user.tickets.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = current_user.tickets.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = current_user.tickets.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = current_user.tickets.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = current_user.tickets.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	  <small>
	    <%= link_to "JIRA Issue Tracker", "http://omrails.com/" %> By Eoin Redmond
	  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>


      
      <ul class="nav">
            <li><a class="brand" href="#">JIRA Tracker</a><li> 
            <li><%= link_to "Home", root_path %></li>
      </ul>    
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <nav>
          <ul class="nav">
            <li><%= link_to "About", about_path %></li>
          </ul>  
        <ul class="nav pull-right">
            <% if user_signed_in?  %>
            <li>
                <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search...">
                </form>
              </li>
              <li><%= link_to "Tickets", tickets_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              <% else %>
               <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
        </ul>
      </nav>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Redsers JIRA App</title>
     <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
          <%= render 'layouts/header' %>
        </header>
        <div class="container">
            <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>       
        </div>
            
    </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
    <%= link_to "One Month Rails", "http://omrails.com/" %>
    is a project to teach 
    <%= link_to "Ruby on Rails", "http://rubyonrails.org/" %> 
    in one month. This is the sample application.
</p>

app/views/pages/home.html.erb
 

    <% if user_signed_in?  %>
    <div class="center hero-unit">
    <h2>You are signed in</h2>
  </div>
    <% else %>
<div class="center hero-unit">
    <h1>JIRA Issue Tracker App</h1>
    <h2>
      You've found the home page for the
      <%= link_to "JIRA Issue Tracker", "http://rte.ie" %>
      application. 
    </h2>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>  
  </div>
    <% end %>

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
    <%= f.input :description, as: :text, input_html: { rows: "3"} %>
  	<div class="form-actions">
    	<%= f.button :submit, class: "btn btn-primary" %>
  	</div>
<% end %>

app/views/tickets/_ticket.html.erb
<tr>
	<td><%= ticket.description %></td>
	<td><%= link_to 'Show', ticket %></td>
	<% if current_user == ticket.user %>
		<td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
		<td><%= link_to 'Destroy', ticket, confirm: 'Are you sure?', method: :delete %></td>
	<% else %>
		<td></td>
		<td></td>
	<% end %>
</tr>

app/views/tickets/edit.html.erb
<h2>Editing ticket</h2>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h2>Listing tickets</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
</thead>
<tbody>
  <%= render @tickets %> 
</tbody>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h2>New ticket</h2>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div  class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <%= @ticket.description %>
			</p>
			<p>
				<%= @ticket.user.name %>
			</p>	
			<% if current_user == @ticket.user %>	
				<%= link_to 'Edit', edit_ticket_path(@ticket) %> | 
			<% end %>
			<%= link_to 'Back', tickets_path %>	
		</div>
	</div>
</div>